### ISSUE TITLE
Snappymail upgrade

### ISSUE THREAD

**Issue by master3395** [tbaldur/cyberpanel-mods#1]
Hai, do you know how to upgrade Snappymail also?

Today Snappymail version 2.17.0 is installed.
But I do want to update it to 2.18.1, because it got a new HTML viewer that I need.
I have seen people replace the datafolder, but I am not sure it would work within CyberPanel.

![image](https://user-images.githubusercontent.com/4199669/192107588-d1941c00-cbf0-4f5c-bf47-de87fb8a2559.png)

**Comment by master3395** [comment]
Adding the data folder to the existing, one and replacing the old 2.17.0 number with 2.18.2

**Comment by tbaldur** [comment]
> Adding the data folder to the existing, one and replacing the old 2.17.0 number with 2.18.2

Hello, that was the procedure that you used?

I've been a bit busy lately, but will make sure to add a more with those steps after your feedback

**Comment by tbaldur** [comment]
Alright I checked that $sCustomDataPath need to be populated on the new version, other things are small changes.
Will write the script later today

**Comment by master3395** [comment]
Hai again, sorry for the late reply.
It is only the data folder, and it's name that needs to be updated with each version upgrade, I only imported new files over the existing.
I'm not sure if I need to update some permissions on folders, but so far, everything has gone fine without any permission changes.

**Comment by tbaldur** [comment]
> Hai again, sorry for the late reply. It is only the data folder, and it's name that needs to be updated with each version upgrade, I only imported new files over the existing. I'm not sure if I need to update some permissions on folders, but so far, everything has gone fine without any permission changes.

I believe everything is worked, testes a couple of times.
To make sure, just re-added all the permissions and so on.
Please test it and give me some feedback:
`
sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/snappymail_v_changer.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/snappymail_v_changer.sh)`

**Comment by master3395** [comment]
I tried it on a clean install.
I see no problems so far.

Before:
![image](https://user-images.githubusercontent.com/4199669/192618645-d1784059-e441-4815-915a-e2da55e5c2a6.png)

After running the command :)
![image](https://user-images.githubusercontent.com/4199669/192619682-85224514-d73d-4254-8642-5f2afd9bc2f8.png)
