### ISSUE TITLE
PhpMyAdmin Changer

### ISSUE THREAD

**Issue by master3395** [tbaldur/cyberpanel-mods#2]
Maybe we can have PhpMyAdmin changer like SnappyMail?
My commands below work, as long as your DB works.

https://community.cyberpanel.net/t/how-to-update-phpmyadmin-to-the-latest-version-in-cyberpanel/32224

**Comment by tbaldur** [comment]
Hello,
I will have a look in two days, I'm currently without access to a pc.

**Comment by tbaldur** [comment]
Actually, this should do it @master3395 
Tested a couple of times upgrading/downgrading, but please let me know.

`sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmyadmin_v_changer.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmyadmin_v_changer.sh)`

**Comment by master3395** [comment]
> Actually, this should do it @master3395 Tested a couple of times upgrading/downgrading, but please let me know.
> 
> `sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmyadmin_v_changer.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/phpmyadmin_v_changer.sh)`

Yup this works, just downgraded from 5.2.0 to 5.1.0 and back up to 5.2.0 :)
![image](https://user-images.githubusercontent.com/4199669/208486321-b9be66d0-5c42-4049-a4f2-e5d09767c3c2.png)
