### ISSUE TITLE
Php 8.2?

### ISSUE THREAD

**Issue by master3395** [tbaldur/cyberpanel-mods#4]
Not sure if 8.2 is out for CyberPanel or OLS yet.

**Comment by rafalohaki** [comment]
![image](https://github.com/tbaldur/cyberpanel-mods/assets/20607107/cd7e4eb6-f384-48d8-b878-eccf7ed1c261)
probably but there is still lack of some modules like ioncube, etc so its better to wait.

**Comment by master3395** [comment]
> 

Did you get 82 installed with CyberPanel?
I still haven't got it installed, even if I upgrade my install.

**Comment by tbaldur** [comment]
Haven't tested it as well, currently not using cyberpanel

**Comment by master3395** [comment]
> 

What are you using?

**Comment by rafalohaki** [comment]
i installed cp on alma8, ran only cp installation, nothing more

**Comment by master3395** [comment]
Did a few changes, but haven't tested yet @tbaldur 
https://github.com/master3395/cyberpanel-mods

**Comment by tbaldur** [comment]
@master3395 thank you.
I tested the lsphp82 and at least for phpmyadmin it's working correctly.
I will update the current script to your approach, easier to maintain

**Comment by tbaldur** [comment]
@master3395 refactored the phpmod.sh
It now uses less redundancy as you did on yours and it will install the lsphp if it's missing
Can you test it, please?

**Comment by master3395** [comment]
Sure, i can test :)

**Comment by master3395** [comment]
> @master3395 refactored the phpmod.sh It now uses less redundancy as you did on yours and it will install the lsphp if it's missing Can you test it, please?

Does not seem to change anything.
Tried all options, but no change at all.

![image](https://github.com/tbaldur/cyberpanel-mods/assets/4199669/2d3ddf83-a6e0-44a4-b6c4-1f51d08bcd13)
![image](https://github.com/tbaldur/cyberpanel-mods/assets/4199669/d88a7844-5fa2-4809-9348-d1e49a39e57e)

**Comment by master3395** [comment]
It seems to have installed the latest php version, which I didn't even know was released.
I thought Php 8.2.5 was the latest.
![image](https://github.com/tbaldur/cyberpanel-mods/assets/4199669/69738c6d-3a34-496c-a536-9bcc094067da)

**Comment by tbaldur** [comment]
Check this command:
`ls -la /usr/local/lscp/fcgi-bin/lsphp`
If it says the version that you changed to as the link, then it should be some cache going on (need to look)

**Comment by master3395** [comment]
I did the command, and it does show 80
I deleted all cache on the IP, and logged in again.
Still showing 74 on SnappyMail and PhpMyAdmin.
![image](https://github.com/tbaldur/cyberpanel-mods/assets/4199669/b2156e8d-9922-40bf-a786-cececb4bec57)

**Comment by master3395** [comment]
I did the command, and it does show 80
I deleted all cache on the IP, and logged in again.
Still showing 74 on SnappyMail and PhpMyAdmin.
![image](https://github.com/tbaldur/cyberpanel-mods/assets/4199669/70aae7ab-547d-4b0e-a6f6-d34b72db40fa)

**Comment by tbaldur** [comment]
Alright, going do a fresh install of the latest version to see what's happening and why it's not using the version we changed

**Comment by tbaldur** [comment]
Alright, I found that restarting the lscpd service after the change is enough to make it work. Strange as it wasn't needed before.
Added that change to the script

**Comment by master3395** [comment]
Did it show on SnappyMail also by restarting LSCPD?
