### ISSUE TITLE
[reqest] owasp-modsecurity-crs version changer

### ISSUE THREAD

**Issue by rafalohaki** [tbaldur/cyberpanel-mods#5]
path /usr/local/lsws/conf/modsec
dl: https://github.com/coreruleset/coreruleset/archive/refs/tags/v3.3.4.zip

**Comment by tbaldur** [comment]
Hello,
please consider that you first need to install and activate the owsap rules normally through cyberpanel.
After that, you can change the versions at will.

`sh <(curl https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/modsec_rules_v_changer.sh || wget -O - https://raw.githubusercontent.com/tbaldur/cyberpanel-mods/main/modsec_rules_v_changer.sh)`

**Comment by rafalohaki** [comment]
Thanks a lot!
