### ISSUE TITLE
Internal CyberPanel Upgrade suggestion?

### ISSUE THREAD

**Issue by master3395** [tbaldur/cyberpanel-mods#8]
Trying to make an internal upgrade of CyberPanel, but I am stuck on permission and or execution.
Do you have any suggestions on what to do?
https://github.com/usmannasir/cyberpanel/pull/1139/

**Comment by tbaldur** [comment]
Hello, as you can tell been some time away from here.
I saw it briefly on the URL provided.
My suggestion would be to have a standalone updater script instead, I wouldn't trust cyberpanel to manage its update as sometimes even normal installations from inside cyberpanel break.
